---
title: "Homework 1"
output: github_document
---

This is my solution to HW1! 

```{r}
library(tidyverse)
```

## Problem 1

Create a data frame with specified elements. 

```{r create_df}
prob1_df <-
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
  )
```

Take the mean of each variable in my data frame.
```{r}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

I can take the mean of numbers and logical but not character or factor
```{r results=hide}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

```{r}
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

## Problem 2

```{r}
data("penguins", package = "palmerpenguins")
```

The penguins data set number of columns and rows.

```{r}
ncol(penguins)
nrow(penguins)
```

Mean of Flipper Length
```{r}
mean(penguins$flipper_length_mm, na.rm=T)
```


Scatterplot
```{r}
penguins %>%
  ggplot(aes(x=bill_length_mm, , y=flipper_length_mm, color=species)) +
  geom_point() +
  xlab("Bill Length") +
  ylab("Flipper Length")

ggsave
```

